{{- if .Values.ingress.enabled }}
{{- if .Values.ingress.tls }}
{{- if .Values.ingress.tls.certificate }}
{{- if .Values.ingress.tls.key }}
apiVersion: v1
kind: Secret
type: kubernetes.io/tls
metadata:
  name: "{{ .Release.Name }}-tls"
  labels:
    app: "{{ .Release.Name }}-app"
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
data:
  tls.crt: "{{ .Values.ingress.tls.certificate }}"
  tls.key: "{{ .Values.ingress.tls.key }}"
{{- end }}
{{- end }}
{{- end }}
{{- end }}
