apiVersion: v1
kind: Service
metadata:
  name: "{{ .Release.Name }}-app"
  labels:
    app: "{{ .Release.Name }}-app"
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  type: {{ .Values.serviceType }}
  ports:
  - name: api
    port: {{ .Values.service.publicPort | int }}
    targetPort: {{ .Values.service.apiPort | int }}
    protocol: TCP
  selector:
    app: "{{ .Release.Name }}-app"
